config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"

  resources :wish_lists

  root "wish_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

    private
    def render_not_found
      render file: "#{Rails.root}/public/404.html", status:404, layout: false
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end

    def contact
    end

    def home
    end
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
  before_action :find_wish_list, only: [:show, :edit, :update, :destroy]
    def index
        @wish_lists = WishList.all
    end

    def new
      @wish_list = WishList.new
    end

    def create
      @wish_list = WishList.new(wish_list_params)
      if @wish_list.save
        redirect_to root_path, notice: "成功新增許願卡"
      else
        render :new
      end
    end
    def show
    end

    def edit
    end

    def update
      if @wish_list.update(wish_list_params)
        redirect_to root_path, notice: "更新成功"
      else
        render :edit
      end
    end

    def destroy
      @wish_list.destroy
      redirect_to root_path, notice: "刪除成功"
    end
   
    private
    def find_wish_list
      @wish_list = WishList.find(params[:id])
    end

    def wish_list_params
      params.require(:wish_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於我們<h1>
<%# <a href="/contact">聯絡</a> %>
<%# <%= link_to "聯絡", "/contact" %>
<%= link_to "聯絡", contact_path %>
<%# <%= link_to "聯絡", contact_url %>
<%= link_to "首頁", root_path %>

app/views/pages/contact.html.erb
<h1>聯絡我們<h1>
<%# <a href="/about">關於</a> %>
<%# <%= link_to "關於", "/about" %>
<%= link_to "關於", about_path %>
<%= link_to "首頁", root_path %>

app/views/pages/home.html.erb
<h1>首頁<h1>

app/views/shared/_flash.html.erb
 <% if flash.any? %>
    <div style="background-color: green; color: white">
      <%= notice %>
    </div>
    <div style="background-color: red; color: white">
      <%= alert %>
    </div>
  <% end %>

app/views/wish_list/new_wish.html.erb
<h1>新增許願卡<h1>


  
  <%= form_for @wish_list, url:"/wish_card_list" do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/wish_lists/_form.html.erb
<%= form_with(model: wish_list) do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/wish_lists/edit.html.erb
<h1>編輯 WishList</h1>
<%= render "form", wish_list: @wish_list %>

app/views/wish_lists/index.html.erb
<h1>許願卡、清單<h1>
<%= link_to "新增許願卡", new_wish_list_path %>
<% @wish_lists.each do |wish_list|%>
  <li>
   <%= link_to "編輯", edit_wish_list_path(wish_list)%>
   <%= link_to "刪除", wish_list_path(wish_list), method: "delete", data: {confirm: "確定嗎"} %>
  <%= link_to wish_list.title, wish_list_path(wish_list)%>
  </li>
<% end %>

app/views/wish_lists/new.html.erb
<h1>新增許願卡<h1>
<%= render "form", wish_list: @wish_list %>

app/views/wish_lists/show.html.erb
<section>
  <header>
    <h1><%= @wish_list.title %></h1>
  </header>
  <article>
    <%= simple_format(@wish_list.description) %>
  </article>
</section>